#Basic Python 

##1.Split this string 

In [3]:
s = "Hi there Sam!"

In [4]:
print(s.split())

['Hi', 'there', 'Sam!']


#2.Use .format() to print the following string

##Output should be:The diameter of Earth is 12742 kilometers

In [5]:
planet="Earth"
diameter=12742

In [6]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


#3.In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
#In this nest dictionary grabing the word "Hello"
print(d['k1'][3]['tricky'][3]['target'][3])

hello


#Numpy

In [9]:
import numpy as np

##4.1 Create an array of 15 zeros?

##4.2 Create an array of 15 fives?

In [10]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(15)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#5. Create an array of all the even integers from 20 to 40

In [12]:
np.array([int(i) for i in range(20,40,2)])

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

#6.Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#7. Concatenate a and b

##a=np.array([1,2,3,4,5]),b=np.array([6,7,8,9,10])

In [14]:
np.concatenate((np.array([1,2,3,4,5]),np.array([6,7,8,9,10])))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Pandas

##8.Create a dataframe with 3 rows and 3 columns

In [15]:
import pandas as pd

In [16]:
A = np.random.randint(10, size=(3,3))
#dataframe
df = pd.DataFrame(A,columns=['A','B','C'])
df

A  B  C
0  2  3  9
1  4  4  6
2  4  0  0

#Generate the series of dates from 1st may,2023 to 30th may,2023

In [17]:
import pandas as pd

# calling DataFrame constructor
df = pd.DataFrame()

# Create 6 dates
df['time'] = pd.date_range(start="1/5/2023",end="31/5/2023", freq ='24H')
  # print dataframe

# Exteact features - year, month, day, hour, and minute
df['year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day


# show six rows
df.head(len(df["time"]))

time  year  month  day
0   2023-01-05  2023      1    5
1   2023-01-06  2023      1    6
2   2023-01-07  2023      1    7
3   2023-01-08  2023      1    8
4   2023-01-09  2023      1    9
..         ...   ...    ...  ...
142 2023-05-27  2023      5   27
143 2023-05-28  2023      5   28
144 2023-05-29  2023      5   29
145 2023-05-30  2023      5   30
146 2023-05-31  2023      5   31

[147 rows x 4 columns]

#10. Create 2D list to DataFrame

###lists = [[1,'AAA',10],[2,'BBB',20],[3,'CCC',30]]

In [18]:
lists = [[1, 'AAA', 10], [2, 'BBB', 20], [3, 'CCC', 30]]
pd.DataFrame(lists)

0    1   2
0  1  AAA  10
1  2  BBB  20
2  3  CCC  30